language: node_js
node_js: 
  # - lts/* #设置语言版本，lts表示稳定版
  # - node # latest stable Node.js release
  - 16
branches:
  only:
    - feature #设置只监听哪个分支
cache:
  apt: false
  yarn: false
  directories: 
    - node_modules #缓存依赖
before_install:
- export TZ='Asia/Shanghai' # 设置时区

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true # 创建增量提交而不是执行推送
  on:
    branch: feature
  local_dir: build # 推送到 GitHub 页面的目录
  target_branch: master # 强制推送的分支
  fqdn: wiki.lihx.top
  deployment_file: true # 允许创建部署信息文件

install: # 安装依赖
  # - npm cache clear --force
  - npm install

script:  # 需要执行的脚本
    # - node ./replaceImg.js
    - npm run build
    # - cp ./README.md ./build/README.md
    # - sed -i 's/\r//' deploy.sh
    # - bash ./deploy.sh

after_success: # script 阶段成功时执行
