language: node_js
node_js: 
  - lts/* #设置语言版本，lts表示稳定版
branches:
  only:
    - feature #设置只监听哪个分支
cache:
  apt: false
  yarn: false
  directories: 
    - node_modules #缓存依赖
before_install:
- export TZ='Asia/Shanghai'  # 设置时区

install:  # 安装依赖
  # - npm cache clear --force
  - npm install

script:  # 需要执行的脚本
    # - node ./generateMD.js
    # - node ./replaceImg.js
    - npm run build
    - sed -i 's/\r//' deploy.sh
    - bash ./deploy.sh

after_success: # script 阶段成功时执行
# - scp  -o stricthostkeychecking=no -r ./dist/* root@122.12.11.29:/home/www/blog  # 使用scp拷贝到服务